# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', picklefield.fields.PickledObjectField(default=None, editable=False)),
                ('diseaseState', models.CharField(db_index=True, max_length=100)),
                ('medians', picklefield.fields.PickledObjectField(editable=False)),
                ('standardDeviations', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
