# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20170201_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='UserProbability',
        ),
        migrations.RemoveField(
            model_name='visualization',
            name='UserResult',
        ),
    ]
