# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_auto_20170215_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualization',
            name='UserProbability',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='visualization',
            name='UserResult',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
