# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_auto_20170225_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualization',
            name='UserProbability',
        ),
        migrations.RemoveField(
            model_name='visualization',
            name='UserResult',
        ),
    ]
